### ISSUE TITLE
Use ProGuard 7 without hard dependency on Android

### ISSUE THREAD

**Issue by suushiemaniac** [Guardsquare/proguard#66] opened 2020-08-09 16:13 UTC
I am currently using ProGuard 6 to minify a JAR that has absolutely nothing to do with Android.

It is a plain Gradle project setup, but when I replace `net.sf.proguard:proguard-gradle:6.2.2` with `com.guardsquare:proguard-gradle:7.0.0` the Gradle configuration fails:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
     Required by:
         project : > com.guardsquare:proguard-gradle:7.0.0
```

I'd love to continue using the newer versions of ProGuard without having to include Android dependencies in my project. For the record, I have added JCenter to my repositories as you can see in the error output above.

**Comment by giacomoferretti** [comment] 2020-08-10 12:49
You'll need to add `google()` in your `buildscript.repositories` block.

**Comment by suushiemaniac** [comment] 2020-08-10 12:59
I understand that, but doing so would allow ProGuard to find the Android Build tools dependency and needlessly include it in my non-Android project.

The purpose of this issue is to discuss whether including a compile dependency on Android Build Tools is really necessary (and if so, understand why).

**Comment by giacomoferretti** [comment] 2020-08-10 13:20
I edited my comment shortly after. Check the new version.

**Comment by suushiemaniac** [comment] 2020-08-10 15:45
Based on your updated comment I can confirm that excluding Android Build Tools works. Thanks for the hint and support!

However seeing that change in action I cannot help but wonder why the dependency is there in the first place? Evidently, it is not required to run ProGuard...

**Comment by dzan** [comment] 2020-08-11 09:47
Duplicate of #30

**Closed** 2020-12-15 10:44 UTC
Labels: bug, packaging
