### ISSUE TITLE
Support for Java 22

### ISSUE THREAD

**Issue by xberkhout** [Guardsquare/proguard#387] opened 2024-02-13 14:03 UTC
As the first release candidate of Java 22 has arrived (https://openjdk.org/projects/jdk/22/) it would be nice if support would be added in the next patch/release. I hope it is just changing the allowed class file version to 66. Maybe directly do it for Java 23 so 67 (https://javaalmanac.io/bytecode/versions/) as early access build for Java 23 are also available (https://jdk.java.net/23/).

I would like to try out the new JEP 454: Foreign Function & Memory API and use it in my build process.

**Comment by mrjameshamilton** [comment] 2024-02-13 17:47
It looks like none of the features or changes in Java 22 require any special handling by ProGuard beyond the version number (e.g. no new attributes, bytecode instructions).

Could you make a PR with the required changes, similar to the changes made for Java 21? https://github.com/Guardsquare/proguard-core/pull/92

**Comment by henm** [comment] 2024-03-20 13:39
I would also like to use Java 22 with proguard, so I created a PR similar to the one for Java 21 mentioned above: https://github.com/Guardsquare/proguard-core/pull/127

Thanks!

**Comment by mipastgt** [comment] 2024-03-27 09:19
The changes made by @henm have been merged already. Can we also expect a release in the near future :-? That would be great.

**Comment by eduveks** [comment] 2024-03-28 20:45
The support to Java 22 urges!

```
Caused by: java.lang.UnsupportedOperationException: Unsupported version number [66.0] (maximum 65.65535, Java null)
```

Please as soon as possible! We need 🚀

Thank you 🙌

**Comment by lordarnoud** [comment] 2024-03-29 13:05
Came here as well to look for a release date on the Java 22 support in maven! I am currently migrating the application from Java 8 to 22 and found out it uses proguard and now I am stuck on the final step before being able to release :(

**Comment by xxDark** [comment] 2024-04-02 14:03
I just stumbled across the same problem. I made a [tool](https://github.com/xxDark/versionchanger.git) that can change classfile version in one go in directories/zip archives/single files.
The command line syntax is `... majorVersionFrom majorVersionTo file1 file2 file3 "file4"`
(majorVersion is the JDK version, not classfile version)
Example use is as follows (Change version in shadow jar, from 22 to 21):
```kotlin

val changeVersion = tasks.register<JavaExec>("changeVersion") {
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(17))
    })
    classpath(project.file("versionchanger.jar"))
    mainClass.set("dev.xdark.versionchanger.CLI")

    args(
        listOf("22", "21") + listOf(project1, project2, project3)
                .map { it.tasks.shadowJar.get().archiveFile.get().asFile.absolutePath }
    )
}
```
Hope someone finds this useful.

**Comment by mipastgt** [comment] 2024-04-02 14:43
@xxDark What makes you think that an incompatible class file gets compatible by just changing a number in it? This may just lead to difficult to trace crashes.

**Comment by xxDark** [comment] 2024-04-02 14:53
> @xxDark What makes you think that an incompatible class file gets compatible by just changing a number in it? This may just lead to difficult to trace crashes.

Nothing makes me think that. That is why I put the text in bold.
JDK 22 classfile format did not change (correct me if I'm wrong), and I needed to use Proguard with it. It did not work, so I made that fast tool to change all classfile versions for me.
I'm well aware that classfiles don't get compatible by just changing their major version.

**Comment by lordarnoud** [comment] 2024-04-03 13:58
Is there a release date in sight for this? :) Or any updates on it?

**Comment by mrjameshamilton** [comment] 2024-05-29 16:15
ProGuard 7.5 has just been published with Java 22 support

**Comment by boris-petrov** [comment] 2024-05-29 16:16
Awesome! Thank you!

**Closed by mrjameshamilton** 2024-05-29 16:15 UTC

**Comment by xberkhout** [comment] 2024-05-30 13:51
Thanks a lot!

**Comment by Chinaniu** [comment] 2024-06-26 06:50
When I try to package using JDK 17 and ProGuard 7.5.0 and  proguard-core  is 9.1.1 , I encounter an error 
1.  Caused by: java.lang.UnsupportedOperationException: Unsupported version number [66.0] (maximum 65.65535, Java null), 
2. Caused by: java.io.IOException: Can't process class [org/apache/tomcat/util/net/openssl/panama/OpenSSLContext$1.class] (Unsupported version number [66.0] (maximum 65.65535, Java null)) 
3.java.io.IOException: Can't read [D:\installation\JavaRepository\org\apache\tomcat\embed\tomcat-embed-core\10.1.24\tomcat-embed-core-10.1.24.jar(;;;;;;;;!META-INF/**,!META-INF/versions/17/**.class)] (Can't process class [org/apache/tomcat/util/net/openssl/panama/OpenSSLContext$1.class] (Unsupported version number [66.0] (maximum 65.65535, Java null)))

How should I resolve this issue? What could be the reasons behind it?

**Comment by mrjameshamilton** [comment] 2024-06-26 06:56
Hi @Chinaniu ! You are using an older version of ProGuardCORE 9.1.1 that doesn't support JDK 22. JDK 22 support was added in [ProGuardCORE 9.1.2](https://github.com/Guardsquare/proguard-core/releases/tag/v9.1.2) and ProGuard 7.5 [has a dependency on ProGuardCORE 9.1.4](https://github.com/Guardsquare/proguard/blob/master/gradle.properties#L4).

**Comment by Chinaniu** [comment] 2024-06-26 07:18
@mrjameshamilton  thanks    then  now is   [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.SignatureParser$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.SignatureParser$ParseResult]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.SignatureParser]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.StringSharingDecompressor]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.StringSharingDecompressorFactory]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.ZipDecompressor]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.decompressor.ZipDecompressorFactory]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageBufferCache$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageBufferCache$2]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageBufferCache]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageHeader]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageLocation]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$Directory]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$LinkNode]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$Node]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$Resource]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$SharedImageReader$LocationVisitor]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader$SharedImageReader]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReader]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReaderFactory$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageReaderFactory]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageStream]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageStrings]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.ImageStringsReader]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.NativeImageBuffer$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jimage.NativeImageBuffer]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.ExplodedImage$PathNode]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.ExplodedImage]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtDirectoryStream$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtDirectoryStream]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileAttributes]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileAttributeView$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileAttributeView$AttrID]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileAttributeView]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileStore]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileSystem$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileSystem]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileSystemProvider$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileSystemProvider$JrtFsLoader]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtFileSystemProvider]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtPath$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtPath$2]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtPath]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.JrtUtils]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.SystemImage$1]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.SystemImage$2]
 [proguard] Note: duplicate definition of library class [jdk.internal.jrtfs.SystemImage]
 [proguard] Note: there were 193 duplicate class definitions.    

How should I resolve this issue?

**Comment by Chinaniu** [comment] 2024-06-27 03:53
When attempting to launch the obfuscated Spring Boot project built with JDK 17 using ProGuard, an error message is encountered during startup.  this is a error Description:

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.   

then  this is my proguard configuration 


-dontshrink


-dontoptimize


-useuniqueclassmembernames


-adaptclassstrings


#-keepparameternames


-keepclassmembers public class * {
    void set*(***);
    *** get*();
}


-keepclassmembers class * implements java.io.Serializable {
    *;
}


-keep class *{
@org.springframework.beans.factory.annotation.Autowired *;
@org.springframework.beans.factory.annotation.Value *;
}


-keepclassmembers class * {
       public static void main(java.lang.String[]);
}

-keep public class * extends org.springframework.boot.web.servlet.server.ServletWebServerFactory { *; }


-ignorewarnings
-dontnote

-printconfiguration


-printseeds

**Comment by mrjameshamilton** [comment] 2024-06-27 07:43
Hi @Chinaniu , for usage questions like that please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.

You'll also find some useful information in the [manual](https://www.guardsquare.com/manual/home) in how to configure ProGuard.
