### ISSUE TITLE
7.2.1 proguardgui unable to save configuration

### ISSUE THREAD

**Issue by toothie123** [Guardsquare/proguard#232] opened 2022-03-22 06:23 UTC
When attempting to save configuration in 7.2.1 proguardgui.bat,  I got this weird popup saying "can't save the configuration file [D:/test.pro]". The target file was created, but appear to be of zero-length. I tried the same on 7.2.0 and it works. My JDK being : 

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**Comment by mrjameshamilton** [comment] 2022-03-23 20:11
Duplicate of https://github.com/Guardsquare/proguard/issues/220

**Closed by mrjameshamilton** 2022-03-23 20:11 UTC
Labels: duplicate
