### ISSUE TITLE
6.2.0 produces: java.lang.VerifyError: Bad invokespecial instruction: current class isn't assignable to reference class.

### ISSUE THREAD

**Issue by swpalmer** [Guardsquare/proguard#10] opened 2019-11-14 22:18 UTC
java.lang.VerifyError: Bad invokespecial instruction: current class isn't assignable to reference class.

Exception Details:
  Location:
    ca/mypackage/one/MyClass$RegistryEntry.getResolvedDefinition()Lca/mypackage/two/MyOtherClass; @52: invokespecial         Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab4 000c 9900 082a b400 0db0 2ab4 000a
    0000010: b400 0959 4cc2 2ab4 000d c700 222a 59b4
    0000020: 000a 2ab4 000b b600 11b5 000d 2ab4 000a
    0000030: 2ab4 000d b700 0e2a 04b5 000c 2bc3 a700
    0000040: 084d 2bc3 2cbf 2ab4 000d b0
  Exception Handler Table:
    bci [22, 62] => handler: 65
    bci [65, 68] => handler: 65
  Stackmap Table:
    same_frame(@12)
    append_frame(@60,Object[#6])
    full_frame(@65,{Top,Object[#6]},{Object[#8]})
    full_frame(@70,{Object[#2]},{})

**Comment by swpalmer** [comment] 2019-11-14 22:19
Building with OpenJDK 13.0.1

**Comment by netomi** [comment] 2019-11-20 09:48
Can you share maybe a reproducible sample for this issue?
Have you tried older versions of ProGuard?

**Comment by swpalmer** [comment] 2019-11-22 14:26
While I can reproduce this 100%, it is with a very large proprietary project.  I have begun an attempt to isolate a reproducible sample that I can share, but it will take some time.
The bug is reproducible with ProGuard 6.1.0  and 6.2.0. Older versions of ProGuard do not support the class version required.

**Comment by swpalmer** [comment] 2019-11-25 20:03
[ProguardTest.zip](https://github.com/Guardsquare/proguard/files/3888501/ProguardTest.zip)
Added reproducible test case.  Simply run gradlew.bat.

**Comment by swpalmer** [comment] 2019-11-25 20:06
Note run "gradlew -Punobfuscated=true" to run the unobfuscated code.  The project is nonsensical at this point as I produced it by removing basically everything I code from a much larger project.  It is very small now, but I removed so much code that what it left doesn't make sense for anything other than to demonstrate this problem.

**Comment by netomi** [comment] 2019-11-25 20:10
Thanks a lot, we will inspect the code.

**Comment by netomi** [comment] 2019-11-25 20:57
I could reproduce the problem.
The issue seems to be the following JEP: http://openjdk.java.net/jeps/181

This allows anonymous inner classes to call private methods in outer classes with invokevirtual.
This was introduced in Java 11, in previous versions this was not supported and the compiler created additional accessor methods in this case.

This should be supported by Proguard already with this change:

[PGD-188] Added support for Java 10, 11, and 12.

Apparently there is a bug which needs to be fixed. A solution would be to switch to a target compatibility < 11 to avoid that the compiler creates byte code that can not be properly handled by ProGuard.

**Comment by swpalmer** [comment] 2019-11-25 21:30
Good that you have an understanding of what it may be.  Hopefully finding what is going wrong there and coming up with a fix won't take too long.  I only encountered this issue because I'm trying to get my own project working with JDK 11+.  So targeting JDK 8 is already where I'm at, but what I'm trying to move past.  Can't get there until the whole tool chain supports it.

**Comment by swpalmer** [comment] 2019-11-27 18:26
Just to clarify something. You mention switching the target compatibility < 11.  That is not possible without also changing the source compatibility as you cannot target Java 10 with source 11, 12 or 13.

**Comment by netomi** [comment] 2019-11-27 18:27
Yes I know, thats unfortunate, and we are looking at this issue with high priority as JDK 11 is already in wide-spread use.

**Comment by netomi** [comment] 2019-11-27 19:46
The problem is fixed and will be included in the next release.

**Closed by netomi** 2019-11-27 19:46 UTC

**Comment by swpalmer** [comment] 2019-11-27 19:55
Excellent news! 
Is there an estimated date for that release?

**Comment by netomi** [comment] 2019-11-27 21:18
We try to make a new release in the next 2 weeks.
