### ISSUE TITLE
JDK 21 Support

### ISSUE THREAD

**Issue by dougxc** [Guardsquare/proguard#332] opened 2023-04-13 08:47 UTC
JDK 21 is going to land in [Sept 2023](https://mail.openjdk.org/pipermail/jdk-dev/2023-April/007566.html). It would be great to have JDK 21 support in ProGuard sometime in advance.

**Comment by mrjameshamilton** [comment] 2023-04-13 21:24
Hi @dougxc ! You weren't the first to ask this time :) I'll close this as a duplicate of #331

**Closed** 2023-04-13 21:25 UTC
