### ISSUE TITLE
Optimizing crashes my program

### ISSUE THREAD

**Issue by Windolian** [Guardsquare/proguard#21] opened 2019-12-18 11:58 UTC
Hello, I am with a problem that if I leave the optimizer on, the program does not work properly when connecting with a lib on Java.
It only works properly after -dontoptimize
I don't have a problem with obfuscating or shrinking, only optimize.

What's the best way to figure out the error? I want to use optimize

Thanks

**Comment by netomi** [comment] 2019-12-18 13:32
You have to give us some context to be able to understand the cause of the problem and possible fixes.

What exceptions do you get? Stacktraces
Do you have a reproducible sample or can share the failing jar file?

**Comment by Windolian** [comment] 2019-12-18 14:14
My proguard configuration is

``<proguard>
			-target 1.3
	 		-dontnote **
	 		-dontwarn
		  	-injars      "${deploy}/${jarNameStart}-clear.jar"
		  	-outjars     "${deploy}/${jarNameStart}-proguard.jar"
			#-dontobfuscate
			#-dontshrink
			-dontoptimize

			
	 		# Save meta-data for stack traces
	 		-renamesourcefileattribute SourceFile
	 		# Keep all annotations and meta-data
	 		-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod
	 		
	 		# Rename FXML files together with related views
	 		-adaptresourcefilenames **.png,**.css, **.gif, **.properties, **.xml, **.jpg
	 		-adaptresourcefilecontents **.properties, META-INF/MANIFEST.MF
	
	 		-flattenpackagehierarchy ''
	 		
	 		-libraryjars "${JAVA_HOME}/lib/dt.jar"
	 		-libraryjars "${JAVA_HOME}/lib/tools.jar"
	 		-libraryjars "${JAVA_HOME}/jre/lib/rt.jar"
	 		-libraryjars "${JAVA_HOME}/jre/lib/jce.jar"
	 		-libraryjars "${JAVA_HOME}/jre/lib/jsse.jar"
	 		-libraryjars "${JAVA_HOME}/jre/lib/plugin.jar"
	 		-libraryjars "${JAVA_HOME}/jre/lib/charsets.jar"
			
			-libraryjars "${lib}/xstream-1.3.1.jar"

	 		# Keep entry-point class
	 		-keep class com.mouse.main.Main {
	 		    public static void main(java.lang.String[]);
	 		}
	 		-keep class com.mouse.main.Main {
	 		    public static void main(java.lang.String[]);
	 		}
	 	
	 		-keepclassmembernames class com.mouse.channel.** {
	 			*;
	 		}
			-keep class com.thoughtworks.xstream.** {
				*;
			}
	 		
	 		# Save meta-data for stack traces
	 		-printmapping out-obf.map
	 		-renamesourcefileattribute SourceFile
	 		-keepattributes SourceFile,LineNumberTable
	
	 		# Keep names of fields marked with @Inject and @PostConstruct attributes
	 		-keepclassmembers class * {
	 		  @javax.inject.Inject *;
	 		  @javax.annotation.PostConstruct *;
	 		}
		</proguard>``

The error appears when I use a seperate lib called XStream.

I can't share a failing jar sorry

![2019-12-18 14_09_05-Screenshot (19) png ‎- Photos](https://user-images.githubusercontent.com/10700657/71093156-8cdd0380-21a0-11ea-8aa3-08360966bc81.png)

**Comment by netomi** [comment] 2019-12-18 14:22
Looks like a problem with serialization / de-serialization of classes.
Maybe due to optimization the class hierarchy is not as expected anymore.

You dont seem to have rules for serializable classes:

# Serializable classes.
-keepclassmembers class * implements java.io.Serializable {
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

I dont know if this is already enough, can you check if this would solve the problem?

**Comment by Windolian** [comment] 2019-12-18 15:16
Unfortunately its still happening. Any ideas on anything else to try or on how to debug the problem?

**Comment by Windolian** [comment] 2019-12-18 17:37
Update 
So I decompiled the Jar I found this:
Before the obfuscation:
`public void setStartService(boolean paramBoolean) { this.startService = (new Boolean(paramBoolean)).toString(); }`
After the obfuscation:
  `public final void setStartService(boolean paramBoolean) { this.startService = Boolean.valueOf(paramBoolean).toString(); }
`
The problem is the Boolean.valueOf was only added in java 1.4 and I am specifically pointing the target to 1.3.
So does the optimization ignore the target? Is this a bug?

**Comment by EricLafortune** [comment] 2019-12-18 17:44
This optimization indeed ignores the target (assuming 1.4 or higher is universal at this point...) You can disable it with

    -optimizations !code/simplification/object

**Comment by netomi** [comment] 2019-12-19 11:37
Can you confirm if the problem is resolved by disabling the specific optimization?

**Comment by Windolian** [comment] 2019-12-19 11:43
It fixed that exact Boolean.valueOf but unfortunately the optimizations are still breaking other parts of the code, because of Java 1.3 so I think the best option is to remove the optimizations from my config.

**Comment by netomi** [comment] 2019-12-19 11:51
you could disable all optimizations that potentially use some unavailable API calls by adding:

-optimizations !code/simplification/*

Could you give this a try?

**Comment by Windolian** [comment] 2019-12-19 12:49
Sure
Yes, its now working, thanks alot! @netomi @EricLafortune 
I also needed to add this to get it fully working, !code/allocation/variable

Side question, my native functions are getting an exception java.lang.UnsatisfiedLinkError
I saw this on stackoverflow
```
-keepclasseswithmembers,allowshrinking,allowoptimization class com.your.packages.** {
    native <methods>;
}
-keepclassmembers class com.your.packages.** {
    native <methods>;
}
```
But I use ant, and <methods> is a XML tag that breaks the ant config file. How can I fix it?

**Comment by netomi** [comment] 2019-12-19 13:00
Great that it works for you.

Regarding the keep rules for native libraries: this is indeed needed for Proguard as Proguard can not modify the JNI interface in native libraries.

Here is an example how you can express such keep rules in xml:

```
    <keepclassmembers implements="java.io.Serializable">
      <field  access    ="static final"
              type      ="long"
              name      ="serialVersionUID" />
      <field  access    ="static final"
              type      ="java.io.ObjectStreamField[]"
              name      ="serialPersistentFields" />
      <method access    ="private"
              type      ="void"
              name      ="writeObject"
              parameters="java.io.ObjectOutputStream" />
      <method access    ="private"
              type      ="void"
              name      ="readObject"
              parameters="java.io.ObjectInputStream" />
      <method type      ="java.lang.Object"
              name      ="writeReplace"
              parameters="" />
      <method type      ="java.lang.Object"
              name      ="readResolve"
              parameters="" />
    </keepclassmembers>
```

**Closed by netomi** 2019-12-19 13:00 UTC
Labels: unsupported target
