### ISSUE TITLE
Property 'keepkotlinmetadata' is not annotated with an input or output annotation

### ISSUE THREAD

**Issue by paplorinc** [Guardsquare/proguard#46] opened 2020-06-11 08:27 UTC
Enabling warnings with latest Gradle reveals some inconsistencies.

```
tasks.withType<ValidatePlugins> {
    failOnWarning.set(false)
    enableStricterValidation.set(false)
}
```

will yield
```
Plugin validation finished with warnings:
  - Warning: Type 'CacheableProguardTask': property 'keepkotlinmetadata' is not annotated with an input or output annotation.
```
for the new property introduced in 7.0.0:
https://github.com/Guardsquare/proguard/blob/3dc5906a6d74c02eb0661dc0a8f9938dc2482109/base/src/proguard/Configuration.java#L419

**Comment by paplorinc** [comment] 2020-06-11 08:46
May be related to https://github.com/Guardsquare/proguard/issues/14

**Comment by ingdas** [comment] 2020-06-17 13:42
Thanks for bringing this to our attention. This is indeed the same problem as #14, which we did not properly address yet. We'll try to schedule this in.

**Comment by dzan** [comment] 2020-06-23 10:30
Duplicate of #14

**Closed by dzan** 2020-06-23 10:30 UTC
