### ISSUE TITLE
5.3.2 to 6.2.0. JNI error: Constructor must call super() or this() before return

### ISSUE THREAD

**Issue by Klayflash** [Guardsquare/proguard#7] opened 2019-10-21 10:30 UTC
Hello.

I'm migrating from 5.3.2 to 6.2.0 proguard. And I have found following error:
```

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Constructor must call super() or this() before return
Exception Details:
  Location:
    com/HelloWorld.<init>()V @0: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b1

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
5.3.2 version works fine.

Replacing assumenosideeffects to assumenoexternalsideeffects removes the error but it produces unexpected output:
> new StringBuilder("greet ").append("string1").append(" ").append("string2");

[proguardConstructorSideEffects.zip](https://github.com/Guardsquare/proguard/files/3750215/proguardConstructorSideEffects.zip)

Which config must be used to preserve 5.3.2 behavior?

**Comment by netomi** [comment] 2019-10-23 20:05
The problem is when specifying also default constructors with -assumenosideeffect, in your case you have this:

```
-assumenosideeffects class java.lang.String {
  public java.lang.String();
  ...
```

and

```
-assumenosideeffects class java.lang.StringBuilder {
  public java.lang.StringBuilder();
  ...
```

This will also mark the default contructor from its super-class (Object) and create problems like you see. This maybe was different in 5.3.2 but you should not use such constructors with ProGuard 6+.

Removing this 2 lines made the sample work.

**Comment by Klayflash** [comment] 2019-10-25 18:25
> Removing this 2 lines made the sample work.

In this case, jadx-gui shows that
`new StringBuilder();`
is not removed.

To remove this, I've added 

```
-assumenoexternalsideeffects class java.lang.StringBuilder {
  public java.lang.StringBuilder();
}
```
(I moved default constructor from assumenosideeffects  to assumenoexternalsideeffects )

**Comment by netomi** [comment] 2019-10-25 20:51
Thats a more correct solution, we actually do something like this by default, many people fall into the trap with constructors and assumenosideeffects.

**Comment by netomi** [comment] 2019-11-20 09:49
Closing this issue as intended behavior, we should improve that part to avoid issues like that.

**Closed by netomi** 2019-11-20 09:49 UTC
