### ISSUE TITLE
Missing input or output annotations in ProGuardTask under Gradle 7.0

### ISSUE THREAD

**Issue by antonulasevich** [Guardsquare/proguard#148] opened 2021-04-16 07:31 UTC
ProGuardTask cannot be used under Gradle 7.0 due to missing input or output annotations on certain task properties:

Task :obfuscate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':obfuscate' (type 'ProGuardTask').
  - Type 'ProGuardTask' property 'adaptclassstrings' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'ProGuardTask' property 'adaptresourcefilecontents' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'ProGuardTask' property 'adaptresourcefilenames' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'ProGuardTask' property 'addconfigurationdebugging' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'ProGuardTask' property 'allowaccessmodification' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by mrjameshamilton** [comment] 2021-04-16 07:37
Hi @antonulasevich ! Thanks for the report, this is a known issue (duplicate of #136) and has been fixed as part of #139.

The fix is in 7.1.0-beta3 which is not yet release, you can build 7.1.0-beta3 from source: https://github.com/Guardsquare/proguard#-building-proguard

**Closed by mrjameshamilton** 2021-04-16 07:37 UTC
Labels: gradle-plugin
